on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: ./mill __.__.test